version: '2'
volumes:
  hass-data:
    external: true
services:
  influxdb:
    restart: always
    build: ./influxdb
    volumes:
      - 'hass-data:/data'
  grafana:
    restart: always
    build: ./grafana
    ports:
      - "80"
    volumes:
      - 'hass-data:/data'
    environment:
        - 'GF_PATHS_DATA=/data/grafana'
        - 'GF_SERVER_HTTP_PORT=80'
        - 'GF_SESSION_PROVIDER=memory'
        - 'GF_AUTH_ANONYMOUS_ENABLED=true'
